name: odm
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - mahotas
  - python=3.9.7
  - pyod
  - pip
  - scikit-learn
  - scikit-image=0.19.2
  - keras
  - hyperopt
  - pydicom
  - gdcm
  - cudatoolkit=11.3.1
  - pytest
  - psutil
  - pip:
      - pylibjpeg[all]
      - tensorflow==2.5.0
      - protobuf==3.19.4
